
server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: video-translation-service
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:videotranslation
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true

# AWS Configuration
aws:
  region: ${AWS_REGION:us-east-1}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  
  # S3 Configuration
  s3:
    bucket-name: ${S3_BUCKET_NAME:video-translation-bucket}
    endpoint: ${S3_ENDPOINT:}
    force-path-style: false
  
  # SQS Configuration
  sqs:
    queue-url: ${SQS_QUEUE_URL:}
  
  # SNS Configuration
  sns:
    topic-arn: ${SNS_TOPIC_ARN:}

# Translation Service Configuration
translation:
  # AWS Translate Configuration
  aws:
    source-language: ${SOURCE_LANGUAGE:auto}
    target-languages:
      - english
      - arabic
      - korean
      - chinese
      - tamil
      - hindi
  
  # Google Translate Configuration (alternative)
  google:
    api-key: ${GOOGLE_TRANSLATE_API_KEY:}
    enabled: false

# Audio Processing Configuration
audio:
  chunk-duration: 180 # 3 minutes in seconds
  sample-rate: 16000
  bit-rate: 128000
  format: mp3

# Video Processing Configuration
video:
  supported-formats:
    - mp4
    - avi
    - mov
    - mkv
    - wmv
  max-duration: 3600 # 60 minutes in seconds
  quality:
    video-bitrate: 2000000
    audio-bitrate: 128000
  ffmpeg:
    path: ${FFMPEG_PATH:C:\ffmpeg\bin\ffmpeg.exe}
    ffprobe-path: ${FFPROBE_PATH:C:\ffmpeg\bin\ffprobe.exe}

# Text-to-Speech Configuration
tts:
  aws:
    voice-ids:
      english: Joanna
      arabic: Zeina
      korean: Seoyeon
      chinese: Zhiyu
      tamil: Raveena
      hindi: Aditi
    engine: neural

# Job Processing Configuration
job:
  max-concurrent-jobs: 5
  retry-attempts: 3
  retry-delay: 5000 # 5 seconds
  timeout: 3600000 # 1 hour in milliseconds

# Logging Configuration
logging:
  level:
    com.videoservice: DEBUG
    org.springframework.web: INFO
    software.amazon.awssdk: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET:your-secret-key-here}
    expiration: 86400000 # 24 hours in milliseconds 